	tilepal 0, GRAY, GRAY, ROOF, ROOF, BROWN, GRAY, GRAY, RED
	tilepal 0, RED, WATER, WATER, BROWN, WATER, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, GRAY, GRAY, RED
	tilepal 0, RED, WATER, GRAY, GRAY, WATER, RED, RED, RED
	tilepal 0, ROOF, ROOF, GRAY, BROWN, RED, GRAY, GRAY, BROWN
	tilepal 0, BROWN, GRAY, GRAY, BROWN, WATER, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, RED, RED, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, RED, RED
