SECTION "Pics 1", ROMX

IF GEN_2_GRAPHICS
MoltresPicFront::    INCBIN "gfx/pokemon/gsfront/moltres.pic"
MoltresPicBack::     INCBIN "gfx/pokemon/gsback/moltresb.pic"

TentacoolPicFront::  INCBIN "gfx/pokemon/gsfront/tentacool.pic"
TentacoolPicBack::   INCBIN "gfx/pokemon/gsback/tentacoolb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/gsfront/scyther.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/gsback/scytherb.pic"
StaryuPicFront::     INCBIN "gfx/pokemon/gsfront/staryu.pic"
StaryuPicBack::      INCBIN "gfx/pokemon/gsback/staryub.pic"
BlastoisePicFront::  INCBIN "gfx/pokemon/gsfront/blastoise.pic"
BlastoisePicBack::   INCBIN "gfx/pokemon/gsback/blastoiseb.pic"
PinsirPicFront::     INCBIN "gfx/pokemon/gsfront/pinsir.pic"
PinsirPicBack::      INCBIN "gfx/pokemon/gsback/pinsirb.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/gsfront/tangela.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/gsback/tangelab.pic"

JolteonPicFront::    INCBIN "gfx/pokemon/gsfront/jolteon.pic"
JolteonPicBack::     INCBIN "gfx/pokemon/gsback/jolteonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/gsfront/vaporeon.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/gsback/vaporeonb.pic"
MachopPicFront::     INCBIN "gfx/pokemon/gsfront/machop.pic"
MachopPicBack::      INCBIN "gfx/pokemon/gsback/machopb.pic"
ZubatPicFront::      INCBIN "gfx/pokemon/gsfront/zubat.pic"
ZubatPicBack::       INCBIN "gfx/pokemon/gsback/zubatb.pic"
EkansPicFront::      INCBIN "gfx/pokemon/gsfront/ekans.pic"
EkansPicBack::       INCBIN "gfx/pokemon/gsback/ekansb.pic"
ParasPicFront::      INCBIN "gfx/pokemon/gsfront/paras.pic"
ParasPicBack::       INCBIN "gfx/pokemon/gsback/parasb.pic"
PoliwhirlPicFront::  INCBIN "gfx/pokemon/gsfront/poliwhirl.pic"
PoliwhirlPicBack::   INCBIN "gfx/pokemon/gsback/poliwhirlb.pic"
PoliwrathPicFront::  INCBIN "gfx/pokemon/gsfront/poliwrath.pic"
PoliwrathPicBack::   INCBIN "gfx/pokemon/gsback/poliwrathb.pic"
WeedlePicFront::     INCBIN "gfx/pokemon/gsfront/weedle.pic"
WeedlePicBack::      INCBIN "gfx/pokemon/gsback/weedleb.pic"
KakunaPicFront::     INCBIN "gfx/pokemon/gsfront/kakuna.pic"
KakunaPicBack::      INCBIN "gfx/pokemon/gsback/kakunab.pic"
BeedrillPicFront::   INCBIN "gfx/pokemon/gsfront/beedrill.pic"
BeedrillPicBack::    INCBIN "gfx/pokemon/gsback/beedrillb.pic"
ENDC

IF !GEN_2_GRAPHICS
MoltresPicFront::    INCBIN "gfx/pokemon/front/moltres.pic"
MoltresPicBack::     INCBIN "gfx/pokemon/back/moltresb.pic"

TentacoolPicFront::  INCBIN "gfx/pokemon/front/tentacool.pic"
TentacoolPicBack::   INCBIN "gfx/pokemon/back/tentacoolb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/front/scyther.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/back/scytherb.pic"
StaryuPicFront::     INCBIN "gfx/pokemon/front/staryu.pic"
StaryuPicBack::      INCBIN "gfx/pokemon/back/staryub.pic"
BlastoisePicFront::  INCBIN "gfx/pokemon/front/blastoise.pic"
BlastoisePicBack::   INCBIN "gfx/pokemon/back/blastoiseb.pic"
PinsirPicFront::     INCBIN "gfx/pokemon/front/pinsir.pic"
PinsirPicBack::      INCBIN "gfx/pokemon/back/pinsirb.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/front/tangela.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/back/tangelab.pic"

JolteonPicFront::    INCBIN "gfx/pokemon/front/jolteon.pic"
JolteonPicBack::     INCBIN "gfx/pokemon/back/jolteonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/front/vaporeon.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/back/vaporeonb.pic"
MachopPicFront::     INCBIN "gfx/pokemon/front/machop.pic"
MachopPicBack::      INCBIN "gfx/pokemon/back/machopb.pic"
ZubatPicFront::      INCBIN "gfx/pokemon/front/zubat.pic"
ZubatPicBack::       INCBIN "gfx/pokemon/back/zubatb.pic"
EkansPicFront::      INCBIN "gfx/pokemon/front/ekans.pic"
EkansPicBack::       INCBIN "gfx/pokemon/back/ekansb.pic"
ParasPicFront::      INCBIN "gfx/pokemon/front/paras.pic"
ParasPicBack::       INCBIN "gfx/pokemon/back/parasb.pic"
PoliwhirlPicFront::  INCBIN "gfx/pokemon/front/poliwhirl.pic"
PoliwhirlPicBack::   INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PoliwrathPicFront::  INCBIN "gfx/pokemon/front/poliwrath.pic"
PoliwrathPicBack::   INCBIN "gfx/pokemon/back/poliwrathb.pic"
WeedlePicFront::     INCBIN "gfx/pokemon/front/weedle.pic"
WeedlePicBack::      INCBIN "gfx/pokemon/back/weedleb.pic"
KakunaPicFront::     INCBIN "gfx/pokemon/front/kakuna.pic"
KakunaPicBack::      INCBIN "gfx/pokemon/back/kakunab.pic"
BeedrillPicFront::   INCBIN "gfx/pokemon/front/beedrill.pic"
BeedrillPicBack::    INCBIN "gfx/pokemon/back/beedrillb.pic"
ENDC


SECTION "Pics 2", ROMX

IF GEN_2_GRAPHICS
HaunterPicFront::    INCBIN "gfx/pokemon/gsfront/haunter.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/gsback/haunterb.pic"
AbraPicFront::       INCBIN "gfx/pokemon/gsfront/abra.pic"
AbraPicBack::        INCBIN "gfx/pokemon/gsback/abrab.pic"
AlakazamPicFront::   INCBIN "gfx/pokemon/gsfront/alakazam.pic"
AlakazamPicBack::    INCBIN "gfx/pokemon/gsback/alakazamb.pic"
PidgeottoPicFront::  INCBIN "gfx/pokemon/gsfront/pidgeotto.pic"
PidgeottoPicBack::   INCBIN "gfx/pokemon/gsback/pidgeottob.pic"
PidgeotPicFront::    INCBIN "gfx/pokemon/gsfront/pidgeot.pic"
PidgeotPicBack::     INCBIN "gfx/pokemon/gsback/pidgeotb.pic"
StarmiePicFront::    INCBIN "gfx/pokemon/gsfront/starmie.pic"
StarmiePicBack::     INCBIN "gfx/pokemon/gsback/starmieb.pic"
RedPicBack::         INCBIN "gfx/gstrainers/redb.pic"
OldManPicBack::      INCBIN "gfx/gstrainers/oldmanb.pic"

GastlyPicFront::     INCBIN "gfx/pokemon/gsfront/gastly.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/gsback/gastlyb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/gsfront/vileplume.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/gsback/vileplumeb.pic"
ENDC

IF !GEN_2_GRAPHICS
HaunterPicFront::    INCBIN "gfx/pokemon/front/haunter.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/back/haunterb.pic"
AbraPicFront::       INCBIN "gfx/pokemon/front/abra.pic"
AbraPicBack::        INCBIN "gfx/pokemon/back/abrab.pic"
AlakazamPicFront::   INCBIN "gfx/pokemon/front/alakazam.pic"
AlakazamPicBack::    INCBIN "gfx/pokemon/back/alakazamb.pic"
PidgeottoPicFront::  INCBIN "gfx/pokemon/front/pidgeotto.pic"
PidgeottoPicBack::   INCBIN "gfx/pokemon/back/pidgeottob.pic"
PidgeotPicFront::    INCBIN "gfx/pokemon/front/pidgeot.pic"
PidgeotPicBack::     INCBIN "gfx/pokemon/back/pidgeotb.pic"
StarmiePicFront::    INCBIN "gfx/pokemon/front/starmie.pic"
StarmiePicBack::     INCBIN "gfx/pokemon/back/starmieb.pic"
RedPicBack::         INCBIN "gfx/player/redb.pic"
OldManPicBack::      INCBIN "gfx/battle/oldmanb.pic"

GastlyPicFront::     INCBIN "gfx/pokemon/front/gastly.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/back/gastlyb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/front/vileplume.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/back/vileplumeb.pic"
ENDC


SECTION "Pics 3", ROMX

; Removed 'mon sprites from here


SECTION "Pics 4", ROMX

; Removed 'mon sprites from here


SECTION "Pics 5", ROMX

; Removed 'mon sprites from here


SECTION "Pics 6", ROMX

TrainerPics::
IF GEN_2_GRAPHICS
YoungsterPic::     INCBIN "gfx/gstrainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/gstrainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/gstrainers/lass.pic"
SailorPic::        INCBIN "gfx/gstrainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/gstrainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/gstrainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/gstrainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/gstrainers/supernerd.pic"
HikerPic::         INCBIN "gfx/gstrainers/hiker.pic"
BikerPic::         INCBIN "gfx/gstrainers/biker.pic"
BurglarPic::       INCBIN "gfx/gstrainers/burglar.pic"
EngineerPic::      INCBIN "gfx/gstrainers/engineer.pic"
FisherPic::        INCBIN "gfx/gstrainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/gstrainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/gstrainers/cueball.pic"
GamblerPic::       INCBIN "gfx/gstrainers/gambler.pic"
BeautyPic::        INCBIN "gfx/gstrainers/beauty.pic"
PsychicPic::       INCBIN "gfx/gstrainers/psychic.pic"
RockerPic::        INCBIN "gfx/gstrainers/rocker.pic"
JugglerPic::       INCBIN "gfx/gstrainers/juggler.pic"
TamerPic::         INCBIN "gfx/gstrainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/gstrainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/gstrainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/gstrainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/gstrainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/gstrainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/gstrainers/giovanni.pic"
RocketPic::        INCBIN "gfx/gstrainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/gstrainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/gstrainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/gstrainers/bruno.pic"
BrockPic::         INCBIN "gfx/gstrainers/brock.pic"
MistyPic::         INCBIN "gfx/gstrainers/misty.pic"
LtSurgePic::       INCBIN "gfx/gstrainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/gstrainers/erika.pic"
KogaPic::          INCBIN "gfx/gstrainers/koga.pic"
BlainePic::        INCBIN "gfx/gstrainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/gstrainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/gstrainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/gstrainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/gstrainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/gstrainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/gstrainers/channeler.pic"
AgathaPic::        INCBIN "gfx/gstrainers/agatha.pic"
LancePic::         INCBIN "gfx/gstrainers/lance.pic"
ENDC

IF !GEN_2_GRAPHICS
YoungsterPic::     INCBIN "gfx/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/trainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/engineer.pic"
FisherPic::        INCBIN "gfx/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/rocker.pic"
JugglerPic::       INCBIN "gfx/trainers/juggler.pic"
TamerPic::         INCBIN "gfx/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/giovanni.pic"
RocketPic::        INCBIN "gfx/trainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/trainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/bruno.pic"
BrockPic::         INCBIN "gfx/trainers/brock.pic"
MistyPic::         INCBIN "gfx/trainers/misty.pic"
LtSurgePic::       INCBIN "gfx/trainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/trainers/erika.pic"
KogaPic::          INCBIN "gfx/trainers/koga.pic"
BlainePic::        INCBIN "gfx/trainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/trainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/lance.pic"
ENDC


; Inserted pokemon images go here

SECTION "Pics 7", ROMX

IF GEN_2_GRAPHICS
GrowlithePicFront::   INCBIN "gfx/pokemon/gsfront/growlithe.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/gsback/growlitheb.pic"
OnixPicFront::        INCBIN "gfx/pokemon/gsfront/onix.pic"
OnixPicBack::         INCBIN "gfx/pokemon/gsback/onixb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/gsfront/fearow.pic"
FearowPicBack::       INCBIN "gfx/pokemon/gsback/fearowb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/gsfront/pidgey.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/gsback/pidgeyb.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/gsfront/slowpoke.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/gsback/slowpokeb.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/gsfront/kadabra.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/gsback/kadabrab.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/gsfront/graveler.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/gsback/gravelerb.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/gsfront/chansey.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/gsback/chanseyb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/gsfront/machoke.pic"
MachokePicBack::      INCBIN "gfx/pokemon/gsback/machokeb.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/gsfront/mr.mime.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/gsback/mr.mimeb.pic"
HitmonleePicFront::   INCBIN "gfx/pokemon/gsfront/hitmonlee.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/gsback/hitmonleeb.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/gsfront/hitmonchan.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/gsback/hitmonchanb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/gsfront/arbok.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/gsback/arbokb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/gsfront/parasect.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/gsback/parasectb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/gsfront/psyduck.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/gsback/psyduckb.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/gsfront/drowzee.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/gsback/drowzeeb.pic"
GolemPicFront::       INCBIN "gfx/pokemon/gsfront/golem.pic"
GolemPicBack::        INCBIN "gfx/pokemon/gsback/golemb.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/gsfront/magmar.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/gsback/magmarb.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/gsfront/electabuzz.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/gsback/electabuzzb.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/gsfront/magneton.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/gsback/magnetonb.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/gsfront/koffing.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/gsback/koffingb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/gsfront/mankey.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/gsback/mankeyb.pic"
SeelPicFront::        INCBIN "gfx/pokemon/gsfront/seel.pic"
SeelPicBack::         INCBIN "gfx/pokemon/gsback/seelb.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/gsfront/diglett.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/gsback/diglettb.pic"
TaurosPicFront::      INCBIN "gfx/pokemon/gsfront/tauros.pic"
TaurosPicBack::       INCBIN "gfx/pokemon/gsback/taurosb.pic"
ENDC

IF !GEN_2_GRAPHICS
GrowlithePicFront::   INCBIN "gfx/pokemon/front/growlithe.pic"
GrowlithePicBack::    INCBIN "gfx/pokemon/back/growlitheb.pic"
OnixPicFront::        INCBIN "gfx/pokemon/front/onix.pic"
OnixPicBack::         INCBIN "gfx/pokemon/back/onixb.pic"
FearowPicFront::      INCBIN "gfx/pokemon/front/fearow.pic"
FearowPicBack::       INCBIN "gfx/pokemon/back/fearowb.pic"
PidgeyPicFront::      INCBIN "gfx/pokemon/front/pidgey.pic"
PidgeyPicBack::       INCBIN "gfx/pokemon/back/pidgeyb.pic"
SlowpokePicFront::    INCBIN "gfx/pokemon/front/slowpoke.pic"
SlowpokePicBack::     INCBIN "gfx/pokemon/back/slowpokeb.pic"
KadabraPicFront::     INCBIN "gfx/pokemon/front/kadabra.pic"
KadabraPicBack::      INCBIN "gfx/pokemon/back/kadabrab.pic"
GravelerPicFront::    INCBIN "gfx/pokemon/front/graveler.pic"
GravelerPicBack::     INCBIN "gfx/pokemon/back/gravelerb.pic"
ChanseyPicFront::     INCBIN "gfx/pokemon/front/chansey.pic"
ChanseyPicBack::      INCBIN "gfx/pokemon/back/chanseyb.pic"
MachokePicFront::     INCBIN "gfx/pokemon/front/machoke.pic"
MachokePicBack::      INCBIN "gfx/pokemon/back/machokeb.pic"
MrMimePicFront::      INCBIN "gfx/pokemon/front/mr.mime.pic"
MrMimePicBack::       INCBIN "gfx/pokemon/back/mr.mimeb.pic"
HitmonleePicFront::   INCBIN "gfx/pokemon/front/hitmonlee.pic"
HitmonleePicBack::    INCBIN "gfx/pokemon/back/hitmonleeb.pic"
HitmonchanPicFront::  INCBIN "gfx/pokemon/front/hitmonchan.pic"
HitmonchanPicBack::   INCBIN "gfx/pokemon/back/hitmonchanb.pic"
ArbokPicFront::       INCBIN "gfx/pokemon/front/arbok.pic"
ArbokPicBack::        INCBIN "gfx/pokemon/back/arbokb.pic"
ParasectPicFront::    INCBIN "gfx/pokemon/front/parasect.pic"
ParasectPicBack::     INCBIN "gfx/pokemon/back/parasectb.pic"
PsyduckPicFront::     INCBIN "gfx/pokemon/front/psyduck.pic"
PsyduckPicBack::      INCBIN "gfx/pokemon/back/psyduckb.pic"
DrowzeePicFront::     INCBIN "gfx/pokemon/front/drowzee.pic"
DrowzeePicBack::      INCBIN "gfx/pokemon/back/drowzeeb.pic"
GolemPicFront::       INCBIN "gfx/pokemon/front/golem.pic"
GolemPicBack::        INCBIN "gfx/pokemon/back/golemb.pic"
MagmarPicFront::      INCBIN "gfx/pokemon/front/magmar.pic"
MagmarPicBack::       INCBIN "gfx/pokemon/back/magmarb.pic"
ElectabuzzPicFront::  INCBIN "gfx/pokemon/front/electabuzz.pic"
ElectabuzzPicBack::   INCBIN "gfx/pokemon/back/electabuzzb.pic"
MagnetonPicFront::    INCBIN "gfx/pokemon/front/magneton.pic"
MagnetonPicBack::     INCBIN "gfx/pokemon/back/magnetonb.pic"
KoffingPicFront::     INCBIN "gfx/pokemon/front/koffing.pic"
KoffingPicBack::      INCBIN "gfx/pokemon/back/koffingb.pic"
MankeyPicFront::      INCBIN "gfx/pokemon/front/mankey.pic"
MankeyPicBack::       INCBIN "gfx/pokemon/back/mankeyb.pic"
SeelPicFront::        INCBIN "gfx/pokemon/front/seel.pic"
SeelPicBack::         INCBIN "gfx/pokemon/back/seelb.pic"
DiglettPicFront::     INCBIN "gfx/pokemon/front/diglett.pic"
DiglettPicBack::      INCBIN "gfx/pokemon/back/diglettb.pic"
TaurosPicFront::      INCBIN "gfx/pokemon/front/tauros.pic"
TaurosPicBack::       INCBIN "gfx/pokemon/back/taurosb.pic"
ENDC


SECTION "Pics 8", ROMX

IF GEN_2_GRAPHICS
RhydonPicFront::      INCBIN "gfx/pokemon/gsfront/rhydon.pic"
RhydonPicBack::       INCBIN "gfx/pokemon/gsback/rhydonb.pic"
KangaskhanPicFront::  INCBIN "gfx/pokemon/gsfront/kangaskhan.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/gsback/kangaskhanb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/gsfront/nidoranm.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/gsback/nidoranmb.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/gsfront/clefairy.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/gsback/clefairyb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/gsfront/spearow.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/gsback/spearowb.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/gsfront/voltorb.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/gsback/voltorbb.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/gsfront/nidoking.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/gsback/nidokingb.pic"
SlowbroPicFront::     INCBIN "gfx/pokemon/gsfront/slowbro.pic"
SlowbroPicBack::      INCBIN "gfx/pokemon/gsback/slowbrob.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/gsfront/ivysaur.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/gsback/ivysaurb.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/gsfront/exeggutor.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/gsback/exeggutorb.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/gsfront/lickitung.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/gsback/lickitungb.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/gsfront/exeggcute.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/gsback/exeggcuteb.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/gsfront/grimer.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/gsback/grimerb.pic"
GengarPicFront::      INCBIN "gfx/pokemon/gsfront/gengar.pic"
GengarPicBack::       INCBIN "gfx/pokemon/gsback/gengarb.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/gsfront/nidoranf.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/gsback/nidoranfb.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/gsfront/nidoqueen.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/gsback/nidoqueenb.pic"
CubonePicFront::      INCBIN "gfx/pokemon/gsfront/cubone.pic"
CubonePicBack::       INCBIN "gfx/pokemon/gsback/cuboneb.pic"
RhyhornPicFront::     INCBIN "gfx/pokemon/gsfront/rhyhorn.pic"
RhyhornPicBack::      INCBIN "gfx/pokemon/gsback/rhyhornb.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/gsfront/lapras.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/gsback/laprasb.pic"
ArcaninePicFront::    INCBIN "gfx/pokemon/gsfront/arcanine.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/gsback/arcanineb.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/gsfront/gyarados.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/gsback/gyaradosb.pic"
ShellderPicFront::    INCBIN "gfx/pokemon/gsfront/shellder.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/gsback/shellderb.pic"
ENDC

IF !GEN_2_GRAPHICS
RhydonPicFront::      INCBIN "gfx/pokemon/front/rhydon.pic"
RhydonPicBack::       INCBIN "gfx/pokemon/back/rhydonb.pic"
KangaskhanPicFront::  INCBIN "gfx/pokemon/front/kangaskhan.pic"
KangaskhanPicBack::   INCBIN "gfx/pokemon/back/kangaskhanb.pic"
NidoranMPicFront::    INCBIN "gfx/pokemon/front/nidoranm.pic"
NidoranMPicBack::     INCBIN "gfx/pokemon/back/nidoranmb.pic"
ClefairyPicFront::    INCBIN "gfx/pokemon/front/clefairy.pic"
ClefairyPicBack::     INCBIN "gfx/pokemon/back/clefairyb.pic"
SpearowPicFront::     INCBIN "gfx/pokemon/front/spearow.pic"
SpearowPicBack::      INCBIN "gfx/pokemon/back/spearowb.pic"
VoltorbPicFront::     INCBIN "gfx/pokemon/front/voltorb.pic"
VoltorbPicBack::      INCBIN "gfx/pokemon/back/voltorbb.pic"
NidokingPicFront::    INCBIN "gfx/pokemon/front/nidoking.pic"
NidokingPicBack::     INCBIN "gfx/pokemon/back/nidokingb.pic"
SlowbroPicFront::     INCBIN "gfx/pokemon/front/slowbro.pic"
SlowbroPicBack::      INCBIN "gfx/pokemon/back/slowbrob.pic"
IvysaurPicFront::     INCBIN "gfx/pokemon/front/ivysaur.pic"
IvysaurPicBack::      INCBIN "gfx/pokemon/back/ivysaurb.pic"
ExeggutorPicFront::   INCBIN "gfx/pokemon/front/exeggutor.pic"
ExeggutorPicBack::    INCBIN "gfx/pokemon/back/exeggutorb.pic"
LickitungPicFront::   INCBIN "gfx/pokemon/front/lickitung.pic"
LickitungPicBack::    INCBIN "gfx/pokemon/back/lickitungb.pic"
ExeggcutePicFront::   INCBIN "gfx/pokemon/front/exeggcute.pic"
ExeggcutePicBack::    INCBIN "gfx/pokemon/back/exeggcuteb.pic"
GrimerPicFront::      INCBIN "gfx/pokemon/front/grimer.pic"
GrimerPicBack::       INCBIN "gfx/pokemon/back/grimerb.pic"
GengarPicFront::      INCBIN "gfx/pokemon/front/gengar.pic"
GengarPicBack::       INCBIN "gfx/pokemon/back/gengarb.pic"
NidoranFPicFront::    INCBIN "gfx/pokemon/front/nidoranf.pic"
NidoranFPicBack::     INCBIN "gfx/pokemon/back/nidoranfb.pic"
NidoqueenPicFront::   INCBIN "gfx/pokemon/front/nidoqueen.pic"
NidoqueenPicBack::    INCBIN "gfx/pokemon/back/nidoqueenb.pic"
CubonePicFront::      INCBIN "gfx/pokemon/front/cubone.pic"
CubonePicBack::       INCBIN "gfx/pokemon/back/cuboneb.pic"
RhyhornPicFront::     INCBIN "gfx/pokemon/front/rhyhorn.pic"
RhyhornPicBack::      INCBIN "gfx/pokemon/back/rhyhornb.pic"
LaprasPicFront::      INCBIN "gfx/pokemon/front/lapras.pic"
LaprasPicBack::       INCBIN "gfx/pokemon/back/laprasb.pic"
ArcaninePicFront::    INCBIN "gfx/pokemon/front/arcanine.pic"
ArcaninePicBack::     INCBIN "gfx/pokemon/back/arcanineb.pic"
GyaradosPicFront::    INCBIN "gfx/pokemon/front/gyarados.pic"
GyaradosPicBack::     INCBIN "gfx/pokemon/back/gyaradosb.pic"
ShellderPicFront::    INCBIN "gfx/pokemon/front/shellder.pic"
ShellderPicBack::     INCBIN "gfx/pokemon/back/shellderb.pic"
ENDC


SECTION "Pics 9", ROMX

IF GEN_2_GRAPHICS
ArticunoPicFront::    INCBIN "gfx/pokemon/gsfront/articuno.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/gsback/articunob.pic"
ZapdosPicFront::      INCBIN "gfx/pokemon/gsfront/zapdos.pic"
ZapdosPicBack::       INCBIN "gfx/pokemon/gsback/zapdosb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/gsfront/ditto.pic"
DittoPicBack::        INCBIN "gfx/pokemon/gsback/dittob.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/gsfront/meowth.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/gsback/meowthb.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/gsfront/krabby.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/gsback/krabbyb.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/gsfront/vulpix.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/gsback/vulpixb.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/gsfront/ninetales.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/gsback/ninetalesb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/gsfront/pikachu.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/gsback/pikachub.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/gsfront/raichu.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/gsback/raichub.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/gsfront/dratini.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/gsback/dratinib.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/gsfront/dragonair.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/gsback/dragonairb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/gsfront/kabuto.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/gsback/kabutob.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/gsfront/kabutops.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/gsback/kabutopsb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/gsfront/horsea.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/gsback/horseab.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/gsfront/seadra.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/gsback/seadrab.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/gsfront/sandshrew.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/gsback/sandshrewb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/gsfront/sandslash.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/gsback/sandslashb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/gsfront/omanyte.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/gsback/omanyteb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/gsfront/omastar.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/gsback/omastarb.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/gsfront/jigglypuff.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/gsback/jigglypuffb.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/gsfront/wigglytuff.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/gsback/wigglytuffb.pic"
EeveePicFront::       INCBIN "gfx/pokemon/gsfront/eevee.pic"
EeveePicBack::        INCBIN "gfx/pokemon/gsback/eeveeb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/gsfront/flareon.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/gsback/flareonb.pic"
ENDC

IF !GEN_2_GRAPHICS
ArticunoPicFront::    INCBIN "gfx/pokemon/front/articuno.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/back/articunob.pic"
ZapdosPicFront::      INCBIN "gfx/pokemon/front/zapdos.pic"
ZapdosPicBack::       INCBIN "gfx/pokemon/back/zapdosb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/front/ditto.pic"
DittoPicBack::        INCBIN "gfx/pokemon/back/dittob.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/front/meowth.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/back/meowthb.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/front/krabby.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/back/krabbyb.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/front/vulpix.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/back/vulpixb.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/front/ninetales.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/back/ninetalesb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/front/pikachu.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/back/pikachub.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/front/raichu.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/back/raichub.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/front/dratini.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/back/dratinib.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/front/dragonair.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/back/dragonairb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/front/kabuto.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/back/kabutob.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/front/kabutops.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/back/kabutopsb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/front/horsea.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/back/horseab.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/front/seadra.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/back/seadrab.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/front/sandshrew.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/back/sandshrewb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/front/sandslash.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/back/sandslashb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/front/omanyte.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/back/omanyteb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/front/omastar.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/back/omastarb.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/front/jigglypuff.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/back/jigglypuffb.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/front/wigglytuff.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/back/wigglytuffb.pic"
EeveePicFront::       INCBIN "gfx/pokemon/front/eevee.pic"
EeveePicBack::        INCBIN "gfx/pokemon/back/eeveeb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/front/flareon.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/back/flareonb.pic"
ENDC


SECTION "Pics 10", ROMX

IF GEN_2_GRAPHICS
DodrioPicFront::      INCBIN "gfx/pokemon/gsfront/dodrio.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/gsback/dodriob.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/gsfront/primeape.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/gsback/primeapeb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/gsfront/dugtrio.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/gsback/dugtriob.pic"
VenomothPicFront::    INCBIN "gfx/pokemon/gsfront/venomoth.pic"
VenomothPicBack::     INCBIN "gfx/pokemon/gsback/venomothb.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/gsfront/dewgong.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/gsback/dewgongb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/gsfront/caterpie.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/gsback/caterpieb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/gsfront/metapod.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/gsback/metapodb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/gsfront/butterfree.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/gsback/butterfreeb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/gsfront/machamp.pic"
MachampPicBack::      INCBIN "gfx/pokemon/gsback/machampb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/gsfront/golduck.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/gsback/golduckb.pic"
HypnoPicFront::       INCBIN "gfx/pokemon/gsfront/hypno.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/gsback/hypnob.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/gsfront/golbat.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/gsback/golbatb.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/gsfront/mewtwo.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/gsback/mewtwob.pic"
SnorlaxPicFront::     INCBIN "gfx/pokemon/gsfront/snorlax.pic"
SnorlaxPicBack::      INCBIN "gfx/pokemon/gsback/snorlaxb.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/gsfront/magikarp.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/gsback/magikarpb.pic"
MukPicFront::         INCBIN "gfx/pokemon/gsfront/muk.pic"
MukPicBack::          INCBIN "gfx/pokemon/gsback/mukb.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/gsfront/kingler.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/gsback/kinglerb.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/gsfront/cloyster.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/gsback/cloysterb.pic"
ElectrodePicFront::   INCBIN "gfx/pokemon/gsfront/electrode.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/gsback/electrodeb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/gsfront/clefable.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/gsback/clefableb.pic"
WeezingPicFront::     INCBIN "gfx/pokemon/gsfront/weezing.pic"
WeezingPicBack::      INCBIN "gfx/pokemon/gsback/weezingb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/gsfront/persian.pic"
PersianPicBack::      INCBIN "gfx/pokemon/gsback/persianb.pic"
ENDC

IF !GEN_2_GRAPHICS
DodrioPicFront::      INCBIN "gfx/pokemon/front/dodrio.pic"
DodrioPicBack::       INCBIN "gfx/pokemon/back/dodriob.pic"
PrimeapePicFront::    INCBIN "gfx/pokemon/front/primeape.pic"
PrimeapePicBack::     INCBIN "gfx/pokemon/back/primeapeb.pic"
DugtrioPicFront::     INCBIN "gfx/pokemon/front/dugtrio.pic"
DugtrioPicBack::      INCBIN "gfx/pokemon/back/dugtriob.pic"
VenomothPicFront::    INCBIN "gfx/pokemon/front/venomoth.pic"
VenomothPicBack::     INCBIN "gfx/pokemon/back/venomothb.pic"
DewgongPicFront::     INCBIN "gfx/pokemon/front/dewgong.pic"
DewgongPicBack::      INCBIN "gfx/pokemon/back/dewgongb.pic"
CaterpiePicFront::    INCBIN "gfx/pokemon/front/caterpie.pic"
CaterpiePicBack::     INCBIN "gfx/pokemon/back/caterpieb.pic"
MetapodPicFront::     INCBIN "gfx/pokemon/front/metapod.pic"
MetapodPicBack::      INCBIN "gfx/pokemon/back/metapodb.pic"
ButterfreePicFront::  INCBIN "gfx/pokemon/front/butterfree.pic"
ButterfreePicBack::   INCBIN "gfx/pokemon/back/butterfreeb.pic"
MachampPicFront::     INCBIN "gfx/pokemon/front/machamp.pic"
MachampPicBack::      INCBIN "gfx/pokemon/back/machampb.pic"
GolduckPicFront::     INCBIN "gfx/pokemon/front/golduck.pic"
GolduckPicBack::      INCBIN "gfx/pokemon/back/golduckb.pic"
HypnoPicFront::       INCBIN "gfx/pokemon/front/hypno.pic"
HypnoPicBack::        INCBIN "gfx/pokemon/back/hypnob.pic"
GolbatPicFront::      INCBIN "gfx/pokemon/front/golbat.pic"
GolbatPicBack::       INCBIN "gfx/pokemon/back/golbatb.pic"
MewtwoPicFront::      INCBIN "gfx/pokemon/front/mewtwo.pic"
MewtwoPicBack::       INCBIN "gfx/pokemon/back/mewtwob.pic"
SnorlaxPicFront::     INCBIN "gfx/pokemon/front/snorlax.pic"
SnorlaxPicBack::      INCBIN "gfx/pokemon/back/snorlaxb.pic"
MagikarpPicFront::    INCBIN "gfx/pokemon/front/magikarp.pic"
MagikarpPicBack::     INCBIN "gfx/pokemon/back/magikarpb.pic"
MukPicFront::         INCBIN "gfx/pokemon/front/muk.pic"
MukPicBack::          INCBIN "gfx/pokemon/back/mukb.pic"
KinglerPicFront::     INCBIN "gfx/pokemon/front/kingler.pic"
KinglerPicBack::      INCBIN "gfx/pokemon/back/kinglerb.pic"
CloysterPicFront::    INCBIN "gfx/pokemon/front/cloyster.pic"
CloysterPicBack::     INCBIN "gfx/pokemon/back/cloysterb.pic"
ElectrodePicFront::   INCBIN "gfx/pokemon/front/electrode.pic"
ElectrodePicBack::    INCBIN "gfx/pokemon/back/electrodeb.pic"
ClefablePicFront::    INCBIN "gfx/pokemon/front/clefable.pic"
ClefablePicBack::     INCBIN "gfx/pokemon/back/clefableb.pic"
WeezingPicFront::     INCBIN "gfx/pokemon/front/weezing.pic"
WeezingPicBack::      INCBIN "gfx/pokemon/back/weezingb.pic"
PersianPicFront::     INCBIN "gfx/pokemon/front/persian.pic"
PersianPicBack::      INCBIN "gfx/pokemon/back/persianb.pic"
ENDC


SECTION "Pics 11", ROMX

IF GEN_2_GRAPHICS
BulbasaurPicFront::   INCBIN "gfx/pokemon/gsfront/bulbasaur.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/gsback/bulbasaurb.pic"
VenusaurPicFront::    INCBIN "gfx/pokemon/gsfront/venusaur.pic"
VenusaurPicBack::     INCBIN "gfx/pokemon/gsback/venusaurb.pic"
TentacruelPicFront::  INCBIN "gfx/pokemon/gsfront/tentacruel.pic"
TentacruelPicBack::   INCBIN "gfx/pokemon/gsback/tentacruelb.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/gsfront/goldeen.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/gsback/goldeenb.pic"
SeakingPicFront::     INCBIN "gfx/pokemon/gsfront/seaking.pic"
SeakingPicBack::      INCBIN "gfx/pokemon/gsback/seakingb.pic"
PonytaPicFront::      INCBIN "gfx/pokemon/gsfront/ponyta.pic"
RapidashPicFront::    INCBIN "gfx/pokemon/gsfront/rapidash.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/gsback/ponytab.pic"
RapidashPicBack::     INCBIN "gfx/pokemon/gsback/rapidashb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/gsfront/rattata.pic"
RattataPicBack::      INCBIN "gfx/pokemon/gsback/rattatab.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/gsfront/raticate.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/gsback/raticateb.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/gsfront/nidorino.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/gsback/nidorinob.pic"
NidorinaPicFront::    INCBIN "gfx/pokemon/gsfront/nidorina.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/gsback/nidorinab.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/gsfront/geodude.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/gsback/geodudeb.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/gsfront/porygon.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/gsback/porygonb.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/gsfront/aerodactyl.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/gsback/aerodactylb.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/gsfront/magnemite.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/gsback/magnemiteb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/gsfront/charmander.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/gsback/charmanderb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/gsfront/squirtle.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/gsback/squirtleb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/gsfront/charmeleon.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/gsback/charmeleonb.pic"
WartortlePicFront::   INCBIN "gfx/pokemon/gsfront/wartortle.pic"
WartortlePicBack::    INCBIN "gfx/pokemon/gsback/wartortleb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/gsfront/charizard.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/gsback/charizardb.pic"
FossilKabutopsPic::   INCBIN "gfx/pokemon/front/fossilkabutops.pic"
FossilAerodactylPic:: INCBIN "gfx/pokemon/front/fossilaerodactyl.pic"
GhostPic::            INCBIN "gfx/battle/ghost.pic"
OddishPicFront::      INCBIN "gfx/pokemon/gsfront/oddish.pic"
OddishPicBack::       INCBIN "gfx/pokemon/gsback/oddishb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/gsfront/gloom.pic"
GloomPicBack::        INCBIN "gfx/pokemon/gsback/gloomb.pic"
ENDC

IF !GEN_2_GRAPHICS
BulbasaurPicFront::   INCBIN "gfx/pokemon/front/bulbasaur.pic"
BulbasaurPicBack::    INCBIN "gfx/pokemon/back/bulbasaurb.pic"
VenusaurPicFront::    INCBIN "gfx/pokemon/front/venusaur.pic"
VenusaurPicBack::     INCBIN "gfx/pokemon/back/venusaurb.pic"
TentacruelPicFront::  INCBIN "gfx/pokemon/front/tentacruel.pic"
TentacruelPicBack::   INCBIN "gfx/pokemon/back/tentacruelb.pic"
GoldeenPicFront::     INCBIN "gfx/pokemon/front/goldeen.pic"
GoldeenPicBack::      INCBIN "gfx/pokemon/back/goldeenb.pic"
SeakingPicFront::     INCBIN "gfx/pokemon/front/seaking.pic"
SeakingPicBack::      INCBIN "gfx/pokemon/back/seakingb.pic"
PonytaPicFront::      INCBIN "gfx/pokemon/front/ponyta.pic"
RapidashPicFront::    INCBIN "gfx/pokemon/front/rapidash.pic"
PonytaPicBack::       INCBIN "gfx/pokemon/back/ponytab.pic"
RapidashPicBack::     INCBIN "gfx/pokemon/back/rapidashb.pic"
RattataPicFront::     INCBIN "gfx/pokemon/front/rattata.pic"
RattataPicBack::      INCBIN "gfx/pokemon/back/rattatab.pic"
RaticatePicFront::    INCBIN "gfx/pokemon/front/raticate.pic"
RaticatePicBack::     INCBIN "gfx/pokemon/back/raticateb.pic"
NidorinoPicFront::    INCBIN "gfx/pokemon/front/nidorino.pic"
NidorinoPicBack::     INCBIN "gfx/pokemon/back/nidorinob.pic"
NidorinaPicFront::    INCBIN "gfx/pokemon/front/nidorina.pic"
NidorinaPicBack::     INCBIN "gfx/pokemon/back/nidorinab.pic"
GeodudePicFront::     INCBIN "gfx/pokemon/front/geodude.pic"
GeodudePicBack::      INCBIN "gfx/pokemon/back/geodudeb.pic"
PorygonPicFront::     INCBIN "gfx/pokemon/front/porygon.pic"
PorygonPicBack::      INCBIN "gfx/pokemon/back/porygonb.pic"
AerodactylPicFront::  INCBIN "gfx/pokemon/front/aerodactyl.pic"
AerodactylPicBack::   INCBIN "gfx/pokemon/back/aerodactylb.pic"
MagnemitePicFront::   INCBIN "gfx/pokemon/front/magnemite.pic"
MagnemitePicBack::    INCBIN "gfx/pokemon/back/magnemiteb.pic"
CharmanderPicFront::  INCBIN "gfx/pokemon/front/charmander.pic"
CharmanderPicBack::   INCBIN "gfx/pokemon/back/charmanderb.pic"
SquirtlePicFront::    INCBIN "gfx/pokemon/front/squirtle.pic"
SquirtlePicBack::     INCBIN "gfx/pokemon/back/squirtleb.pic"
CharmeleonPicFront::  INCBIN "gfx/pokemon/front/charmeleon.pic"
CharmeleonPicBack::   INCBIN "gfx/pokemon/back/charmeleonb.pic"
WartortlePicFront::   INCBIN "gfx/pokemon/front/wartortle.pic"
WartortlePicBack::    INCBIN "gfx/pokemon/back/wartortleb.pic"
CharizardPicFront::   INCBIN "gfx/pokemon/front/charizard.pic"
CharizardPicBack::    INCBIN "gfx/pokemon/back/charizardb.pic"
FossilKabutopsPic::   INCBIN "gfx/pokemon/front/fossilkabutops.pic"
FossilAerodactylPic:: INCBIN "gfx/pokemon/front/fossilaerodactyl.pic"
GhostPic::            INCBIN "gfx/battle/ghost.pic"
OddishPicFront::      INCBIN "gfx/pokemon/front/oddish.pic"
OddishPicBack::       INCBIN "gfx/pokemon/back/oddishb.pic"
GloomPicFront::       INCBIN "gfx/pokemon/front/gloom.pic"
GloomPicBack::        INCBIN "gfx/pokemon/back/gloomb.pic"
ENDC


SECTION "Pics 12", ROMX

IF GEN_2_GRAPHICS
BellsproutPicFront::  INCBIN "gfx/pokemon/gsfront/bellsprout.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/gsback/bellsproutb.pic"
WeepinbellPicFront::  INCBIN "gfx/pokemon/gsfront/weepinbell.pic"
WeepinbellPicBack::   INCBIN "gfx/pokemon/gsback/weepinbellb.pic"
VictreebelPicFront::  INCBIN "gfx/pokemon/gsfront/victreebel.pic"
VictreebelPicBack::   INCBIN "gfx/pokemon/gsback/victreebelb.pic"

MewPicFront::         INCBIN "gfx/pokemon/gsfront/mew.pic"
MewPicBack::          INCBIN "gfx/pokemon/gsback/mewb.pic"

FarfetchdPicFront::   INCBIN "gfx/pokemon/gsfront/farfetchd.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/gsback/farfetchdb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/gsfront/venonat.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/gsback/venonatb.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/gsfront/dragonite.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/gsback/dragoniteb.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/gsfront/doduo.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/gsback/doduob.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/gsfront/poliwag.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/gsback/poliwagb.pic"
JynxPicFront::        INCBIN "gfx/pokemon/gsfront/jynx.pic"
JynxPicBack::         INCBIN "gfx/pokemon/gsback/jynxb.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/gsfront/marowak.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/gsback/marowakb.pic"
ENDC

IF !GEN_2_GRAPHICS
BellsproutPicFront::  INCBIN "gfx/pokemon/front/bellsprout.pic"
BellsproutPicBack::   INCBIN "gfx/pokemon/back/bellsproutb.pic"
WeepinbellPicFront::  INCBIN "gfx/pokemon/front/weepinbell.pic"
WeepinbellPicBack::   INCBIN "gfx/pokemon/back/weepinbellb.pic"
VictreebelPicFront::  INCBIN "gfx/pokemon/front/victreebel.pic"
VictreebelPicBack::   INCBIN "gfx/pokemon/back/victreebelb.pic"

MewPicFront::         INCBIN "gfx/pokemon/front/mew.pic"
MewPicBack::          INCBIN "gfx/pokemon/back/mewb.pic"

FarfetchdPicFront::   INCBIN "gfx/pokemon/front/farfetchd.pic"
FarfetchdPicBack::    INCBIN "gfx/pokemon/back/farfetchdb.pic"
VenonatPicFront::     INCBIN "gfx/pokemon/front/venonat.pic"
VenonatPicBack::      INCBIN "gfx/pokemon/back/venonatb.pic"
DragonitePicFront::   INCBIN "gfx/pokemon/front/dragonite.pic"
DragonitePicBack::    INCBIN "gfx/pokemon/back/dragoniteb.pic"
DoduoPicFront::       INCBIN "gfx/pokemon/front/doduo.pic"
DoduoPicBack::        INCBIN "gfx/pokemon/back/doduob.pic"
PoliwagPicFront::     INCBIN "gfx/pokemon/front/poliwag.pic"
PoliwagPicBack::      INCBIN "gfx/pokemon/back/poliwagb.pic"
JynxPicFront::        INCBIN "gfx/pokemon/front/jynx.pic"
JynxPicBack::         INCBIN "gfx/pokemon/back/jynxb.pic"
MarowakPicFront::     INCBIN "gfx/pokemon/front/marowak.pic"
MarowakPicBack::      INCBIN "gfx/pokemon/back/marowakb.pic"
ENDC
